---
platform: linux

image_resource: 
  type: docker-image
  source:
    repository: alpine
    version: 3.4

run:
  path: sh
  args: 
  - -exc
  - |
    apk add --update openssh
    mkdir ~/.ssh
    set +x
    echo "$SSH_KEY" > ~/.ssh/id_rsa
    echo "$SSH_KEY_PUB" > ~/.ssh/id_rsa.pub
    set -x
    chmod 400 ~/.ssh/id_rsa
    chmod 400 ~/.ssh/id_rsa.pub
    ssh \
      -oStrictHostKeyChecking=no \
      -oBatchMode=yes \
      -i ~/.ssh/id_rsa \
      root@concourse.kasterborous.sklirg.io -p 25022 /bin/bash << EOF
        cd /srv/github.com/sklirg/professor-willow
        docker-compose -f .dockerfiles/docker-compose-prod.yml pull
        docker-compose -f .dockerfiles/docker-compose-prod.yml down
        docker-compose -f .dockerfiles/docker-compose-prod.yml up -d
    EOF
