---
platform: linux

image_resource: 
  type: docker-image
  source:
    repository: golang
    version: "1.6"

inputs:
- name: professor-willow

run:
  dir: professor-willow
  path: sh
  args: 
  - -exc
  - |
    curl -s https://glide.sh/get | sh
    glide install
    go build
    go vet
    go test -coverprofile=cover.out -covermode=atomic
